# .github/workflows/deploy.yml
name: Deploy Next.js to Server

on:
  push:
    branches: [ main, dev, ci ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '24.x'
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Build Docker image
      run: |
        docker build -t iffree-front .

    - name: Save Docker image
      run: |
        docker save iffree-front -o iffree-front.tar

    - name: Setup SSH private key
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        echo "$SSH_PRIVATE_KEY" | ssh-add - >/dev/null

    - name: Clean directory
      run: |
        ssh -o StrictHostKeyChecking=no $SERVER_HOST "
          rm -rf $DEPLOY_PATH/* && \
          echo '$ENV_FILE_CONTENT' > $DEPLOY_PATH/.env"

    - name: Copy files
      run: |
        scp -o StrictHostKeyChecking=no iffree-front.tar $SERVER_HOST:$DEPLOY_PATH

    - name: Deploy to server
      run: |
        scp -o StrictHostKeyChecking=no iffree-front.tar $SERVER_HOST:$DEPLOY_PATH
        
        ssh -o StrictHostKeyChecking=no $SERVER_HOST:$DEPLOY_PATH "
          docker load -i /tmp/iffree-front.tar && \
          docker stop iffree-container && \ 
          docker rm iffree-container && \
          docker run -d \
            -p 3000:3000 \
            -e NEXT_PUBLIC_API_URL=http://18.189.243.17:80 \
            --name iffree-container \
            iffree-front
          docker image prune -f
          rm -f iffree-front.tar
        "

    env:
      ENV_FILE_CONTENT: |
        NEXT_PUBLIC_API_URL=http://18.189.243.17:80
      SERVER_HOST: ubuntu@18.189.243.17
      DEPLOY_PATH: /home/ubuntu/iffree-front
